name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build solver
      run: |
        cmake -H. -B_build
        cmake --build _build
        cd _build
        cpack -G "TGZ"
        cd ..
        mv _build/*.tar.gz artifacts
        tree artifacts
